### ISSUE TITLE
cityio is down / 100% choked 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#96] opened 2019-10-08 13:46 UTC

**Comment by agrignard** [comment] 2019-10-08 13:48
it's working for me

**Comment by agrignard** [comment] 2019-10-08 13:51
working from Lyon

**Comment by RELNO** [comment] 2019-10-08 13:51
Dead in Budapest ;)

**Comment by RELNO** [comment] 2019-10-08 14:04
Update:
 Works on 3G connection. Ergo, this is due to some DDoS or firewall 'feature'.

**Comment by yasushisakai** [comment] 2019-10-08 14:24
looks fine. Anything I should try?

**Comment by RELNO** [comment] 2019-10-08 16:02
We managed to run it, but it was choking if more than one machine ran. It's not a cityio problem, but rather a ddos issue

**Comment by agrignard** [comment] 2019-10-08 21:49
Not working from cell phone (3G or 4G) connection in France

**Comment by yasushisakai** [comment] 2019-10-09 01:15
I can't see this by myself but we can try if services like https://1.1.1.1/ works?

**Comment by yasushisakai** [comment] 2019-10-16 20:29
closing since not reproducible, may be TIMEOUT is less forgiving in 3G, LTE networks

**Closed by yasushisakai** 2019-10-16 20:29 UTC
